name: build
run-name: ${{ github.head_ref }}
on: [push]
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          sparse-checkout: 'BudgetingApp'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache-dependency-path: BudgetingApp/package-lock.json

      - name: Install Node modules
        run: |
              cd BudgetingApp && npm ci
      
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: BudgetingApp/node_modules
          key: node_modules-${{hashFiles('BudgetingApp/package-lock.json')}}
          restore-keys: node_modules- # Take any latest cache if failed to find it for current yarn.lock
        
      - name: Cache Gradle Wrapper
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('BudgetingApp/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('BudgetingApp/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-

        # Build Command
      - name: Make Gradlew Executable
        run: cd BudgetingApp/android && chmod +x ./gradlew

      - name: Build Android
        run: |
              cd BudgetingApp/android && ./gradlew assembleDebug --no-daemon && ls BudgetingApp/android/app/build/outputs/apk/

      # Upload to Artifact
      - name: Upload apk artifact
        uses: actions/upload-artifact@v4
        with:
          name: BudgetingApp-debug.apk
          path: "BudgetingApp/android/app/build/outputs/apk/BudgetingApp-debug.apk"